name: CI

on: [push]
jobs: 
    build-test: 
        runs-on: ubuntu-20.04
        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: Cypress Test 
              uses: cypress-io/github-action@v5  
              with:
                start: 'npm run dev'
                build: 'npm run build'

            - uses: actions/upload-artifacts@v3
              if: always()
              with: 
                name: Cypress Results
                path: |
                    cypress/screenshots
                    cypress/videos
                    cypress/results
                if-no-files-found: ignore