name: CI
on: [push]

jobs: 
  build-test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositório de Testes (Seu)
        uses: actions/checkout@v4

      - name: Checkout Aplicação (RWA)
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-realworld-app
          path: app-ui

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # O GitHub Actions já vem com Yarn instalado, 
          # mas podemos habilitar o cache nativo aqui:
          cache: 'yarn'
          cache-dependency-path: 'app-ui/yarn.lock'

      - name: Instalar e Buildar a Aplicação (Yarn)
        run: |
          cd app-ui
          yarn install --frozen-lockfile
          yarn build

      - name: Instalar Dependências de Teste (Seu Repo)
        run: npm install # Ou yarn install, se você usar yarn no seu repo

      - name: Rodar Cypress
        uses: cypress-io/github-action@v6
        with:
          # Usamos o yarn dev apontando para a pasta da aplicação
          start: yarn dev
          working-directory: app-ui
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180 # Aumentei o tempo pois o build do RWA é pesado
          # Indica onde o Cypress deve procurar os testes (na raiz, fora da app-ui)
          project: ../ 

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: Cypress Results
          path: |
            cypress/screenshots
            cypress/videos